front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
booking_page:
    path: /booking/{vehiculeId}
    defaults: { _controller: FrontBundle:Default:booking}


listvehicle_page:
    path: /listvehicle
    defaults: { _controller: FrontBundle:Default:listvehicle}


basket_page:
    path: /basket
    defaults: { _controller: FrontBundle:Panier:affiche}
    
basket_valide:
    path: /basket/valide
    defaults: { _controller: FrontBundle:Panier:Validation}

basket_remove:
    path: /basket/remove/{index}
    defaults: { _controller: FrontBundle:Panier:remove}

payment_page:
    path: /payment
    defaults: { _controller: FrontBundle:Default:payment}

registration_page:
    path: /registration
    defaults: { _controller: FrontBundle:Default:registration}

edit_content:
    path: /edit_content
    defaults: { _controller: FrontBundle:Default:edit_content}

prepare_page:
    path: /prepare
    defaults: { _controller: FrontBundle:Order:prepare}

order_checkout:
    path: /checkout
    defaults: { _controller: FrontBundle:Order:checkout}
order_checkout_success:
    path: /checkout/success
    defaults: { _controller: FrontBundle:Order:checkoutSuccess}