front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
booking_page:
    path: /booking
    defaults: { _controller: FrontBundle:Default:booking}


listvehicle_page:
    path: /listvehicle
    defaults: { _controller: FrontBundle:Default:listvehicle}


basket_page:
    path: /basket
    defaults: { _controller: FrontBundle:Default:basket}


payment_page:
    path: /payment
    defaults: { _controller: FrontBundle:Default:payment}

    
profile_page:
    path: /profile
    defaults: { _controller: FrontBundle:Default:profile}
