<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\Entity\User;
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser(User $user,$em)
    {
        $QuerBuilder = $em->createQueryBuilder();
        $QuerBuilder->select('u')
                ->from('AppBundle:User','u')
                ->where('u.username = :username')
                ->andWhere('u.password = :password')
                ->setParameter('username',$user->getUserName())
                ->setParameter('password',$user->getPassword());
        $query =$QuerBuilder->getQuery();
        return $query->getResult();
    }
}
