<?php

namespace AppBundle\Repository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMarques()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('SELECT v.brand FROM AppBundle:Vehicle v GROUP BY v.brand');
        return $qb->getResult();     
        //return $query->getQuery()->getResult();
    }
}
