security:
    providers:
        admin:
            memory:
                users:
                    admin: { password: secret, roles: [ 'ROLE_ADMIN' ] }
        aimeos_customer:
            entity: { class: AimeosShopBundle:User, property: username }
        in_memory:
            memory: ~
 
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Aimeos\ShopBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
 
    firewalls:
        aimeos_admin:
            pattern:   ^/admin
            anonymous: ~
            provider: admin
            form_login:
                login_path: /admin
                check_path: /admin_check
        aimeos_myaccount:
            pattern: ^/myaccount
            provider: aimeos_customer
            http_basic:
                realm: "MyAccount"
        main:
            anonymous: ~
 
    access_control:
        - { path: ^/admin/.+, roles: ROLE_ADMIN }
        - { path: ^/myaccount, roles: ROLE_USER }