AppBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: float
            nullable: true
        startDate:
            type: datetime
            column: start_date
            nullable: true
        endDate:
            type: datetime
            column: end_date
            nullable: true
        idVehicle:
            type: integer
            column: id_vehicle
            nullable: true
        idUser:
            type: integer
            column: id_user
            nullable: true
    lifecycleCallbacks: {  }
