AppBundle\Entity\Reservation:
    type: entity
    table: reservation
    indexes:
        IDX_42C84955C51D4DF6:
            columns:
                - id_vehicle
        IDX_42C849556B3CA4B:
            columns:
                - id_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        startDate:
            type: datetime
            nullable: true
            column: start_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
        status:
            type: string
            nullable: true
            column: status
    manyToOne:
        idUser:
            targetEntity: User
            joinColumns:
                id_user:
                    referencedColumnName: id
        idVehicle:
            targetEntity: Vehicle
            joinColumns:
                id_vehicle:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
