AppBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: AppBundle\Repository\UtilisateurRepository
    uniqueConstraints:
        UNIQ_2DA1797792FC23A8:
            columns:
                - username_canonical
        UNIQ_2DA17977A0D96FBF:
            columns:
                - email_canonical
        UNIQ_2DA17977C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: true
            column: firstName
        lastName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: true
            column: lastName
        dateOfBirth:
            type: datetime
            nullable: true
            column: date_of_birth
        adress:
            type: string
            nullable: false
            length: 255
            options:
                fixed: true
            column: Adress
        codePostal:
            type: integer
            nullable: true
            options:
                unsigned: false
        ville:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: Ville
        phone:
            type: integer
            nullable: true
            options:
                unsigned: false
        numberLicence:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Number_Licence
    lifecycleCallbacks: {  }
