AppBundle\Entity\Vehicle:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VehicleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        brand:
            type: string
            length: 255
        model:
            type: string
            length: 255
            nullable : true
        serialNumber:
            type: string
            length: 255
            nullable : true
        color:
            type: string
            length: 255
            nullable : true
        licencePlate:
            type: string
            length: 255
            nullable : true
        kilometer:
            type: integer
            nullable : true
        dateOfPurchase:
            type: datetime
            column: date_of_purchase
            nullable : true
        priceOfPurchase:
            type: integer
            column: price_of_purchase
            nullable : true
        availability:
            type: boolean
            nullable : true
        vehicleType:
            type: boolean
            column: vehicle_type
            nullable : true
    lifecycleCallbacks: {  }
